baseURL: http://sincityburgernyc.com/
languageCode: en-us
title: Sin City Burger

theme: restaurantTheme

publishdir: "../docs"

disableKinds:
  - taxonomy
  - taxonomyTerm
  - JSONFeed
  - RSS
  - sitemap

# menu:
#   main:
#     - name: Home
#       pre: home
#       url: /
#       weight: 1
#     - name: Posts
#       pre: pen-tool
#       url: /posts/
#       weight: 2
#     - name: Tags
#       pre: tag
#       url: /tags/
#       weight: 3
